// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38q6VTui04j-9fcihZxUV-WpGCGrVcag',
    appId: '1:334655447861:web:7c6e2091f2b93c316ae27c',
    messagingSenderId: '334655447861',
    projectId: 'pests-identifier-eline',
    authDomain: 'pests-identifier-eline.firebaseapp.com',
    storageBucket: 'pests-identifier-eline.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVh4LGcpxPrlwtBcQ2fmOy1FkKiLjwKxI',
    appId: '1:750142274385:android:ad9c94d0b57f442976f170',
    messagingSenderId: '750142274385',
    projectId: 'eline-ai-pest',
    storageBucket: 'eline-ai-pest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxA21CVKSkqxV95EttBGIkLHVSKKXZrA',
    appId: '1:334655447861:ios:5f3ba409413ab9416ae27c',
    messagingSenderId: '334655447861',
    projectId: 'pests-identifier-eline',
    storageBucket: 'pests-identifier-eline.firebasestorage.app',
    iosBundleId: 'com.garden.pests.ai.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxA21CVKSkqxV95EttBGIkLHVSKKXZrA',
    appId: '1:334655447861:ios:5f3ba409413ab9416ae27c',
    messagingSenderId: '334655447861',
    projectId: 'pests-identifier-eline',
    storageBucket: 'pests-identifier-eline.firebasestorage.app',
    iosBundleId: 'com.garden.pests.ai.ios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA38q6VTui04j-9fcihZxUV-WpGCGrVcag',
    appId: '1:334655447861:web:56a5830eb3f7c04b6ae27c',
    messagingSenderId: '334655447861',
    projectId: 'pests-identifier-eline',
    authDomain: 'pests-identifier-eline.firebaseapp.com',
    storageBucket: 'pests-identifier-eline.firebasestorage.app',
  );
}
